apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-0
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWELASTICSEARCH/data-0
    server: 10.16.103.9
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: data-elasticstack-elasticsearch-data-0
  persistentVolumeReclaimPolicy: Delete