apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWELASTICSEARCH/master-0
    server: 10.16.103.9
  claimRef:
    namespace: {{ .Values.environment }}
    name: data-elasticstack-elasticsearch-master-0
  persistentVolumeReclaimPolicy: Delete