apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-postgresql-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.environment }}
    name: data-postgresql-postgresql-0
  nfs:
    path: /zpool-126262/WWWPG/postgres
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Recycle