apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.environment }}
  name: data-{{ .Release.Name }}-postgresql-0
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi